In [5]:
import numpy as np
 
data = np.array([[10, 7, 4], [3, 2, 1]])
data

array([[10,  7,  4],
       [ 3,  2,  1]])

In [6]:
np.mean(data)

4.5

In [12]:
np.mean(data, axis=1)

array([7., 2.])

In [13]:
np.average(data)

4.5

In [14]:
np.average(data, axis=1)

array([7., 2.])

In [15]:
np.mean(data, axis=0)

array([6.5, 4.5, 2.5])

In [16]:
np.average(data, axis=0)

array([6.5, 4.5, 2.5])

In [19]:
np.average(data, weights=[0,1,1], axis=1)

array([5.5, 1.5])

In [22]:
np.average(data, weights=[2,3,5], axis=1)

array([6.1, 1.7])

In [23]:
np.var(data)

9.583333333333334

In [24]:
np.var(data, axis=0)

array([12.25,  6.25,  2.25])

In [25]:
np.var(data, axis=1)

array([6.        , 0.66666667])

In [26]:
np.std(data)

3.095695936834452

In [27]:
np.std(data, axis=0)

array([3.5, 2.5, 1.5])

In [28]:
np.std(data, axis=1)

array([2.44948974, 0.81649658])

In [29]:
data = np.zeros((2, 1000000))
data[0, :] = 1.0
data[1, :] = 0.1
np.mean(data, dtype=np.float32)
np.mean(data, dtype=np.float64)

0.5499999999999972

In [41]:
data = np.zeros((2, 10))
data[0, :] = 1.0
data[1, :] = 0.1
np.mean(data, dtype=np.float32)
np.mean(data, dtype=np.float64)

0.55