In [22]:
import numpy as np

In [23]:
a = np.arange(0, 20)

In [24]:
a.shape

(20,)

In [25]:
a[0]

0

In [26]:
a[4]

4

In [31]:
a = a.reshape(2,10)

In [32]:
a.shape

(2, 10)

In [33]:
a[0]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a[0][4]

4

In [36]:
a = a.reshape(2,5,2)

In [37]:
a.shape

(2, 5, 2)

In [38]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [39]:
a[0]

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
a[1]

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [41]:
a[0][4]

array([8, 9])

In [42]:
a[0][4][1]

9

In [44]:
b = np.arange(0, 40, 2).reshape(4,5)

In [45]:
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38]])

In [51]:
a_python_list =  [2**x for x in range(10)]

In [52]:
c = []

In [53]:
c.append(a_python_list)

In [54]:
c

[[1, 2, 4, 8, 16, 32, 64, 128, 256, 512]]

In [55]:
c1 = np.array(a_python_list)

In [56]:
c1

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [57]:
zero_array = np.zeros(10)

In [58]:
zero_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
one_array = np.ones(10)

In [62]:
one_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
empty_array = np.empty(100)

In [64]:
empty_array

array([0.00000000e+000, 0.00000000e+000, 4.94065646e-324, 6.95312125e-310,
       4.69362364e-322, 9.65735033e-312, 9.65735033e-312, 9.65735033e-312,
       9.65735032e-312, 9.65735032e-312, 9.65735033e-312, 9.65735033e-312,
       9.65735033e-312, 9.65735033e-312, 9.65735033e-312, 9.65735033e-312,
       9.65735033e-312, 9.65735034e-312, 9.65735034e-312, 9.65735020e-312,
       9.65735021e-312, 9.65735004e-312, 9.65734928e-312, 9.65734928e-312,
       9.65734927e-312, 9.65734927e-312, 9.65734929e-312, 9.65734927e-312,
       9.65734928e-312, 9.65734927e-312, 9.65734928e-312, 9.65735071e-312,
       9.65735071e-312, 9.65735072e-312, 9.65735071e-312, 9.65735071e-312,
       9.65735071e-312, 9.65735072e-312, 9.65735072e-312, 9.65735072e-312,
       9.65735072e-312, 9.65735072e-312, 9.65734902e-312, 9.65734903e-312,
       9.65734904e-312, 9.65734903e-312, 9.65734904e-312, 9.65734904e-312,
       9.65734904e-312, 9.65734904e-312, 9.65734904e-312, 9.65734904e-312,
       9.65734904e-312, 9

In [67]:
lucky_array = np.full((5,5), 13)
lucky_array

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [71]:
diagonal_array = np.eye(5)
diagonal_array

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [72]:
random_array =np.random.random(10)
random_array

array([0.23624679, 0.93200908, 0.73003085, 0.75942117, 0.72149874,
       0.00432536, 0.23218955, 0.54397855, 0.73785957, 0.3642366 ])

In [75]:
linspace_array = np.linspace(100, 200, num=5)
linspace_array

array([100., 125., 150., 175., 200.])