In [1]:
import numpy as np

In [3]:
X = np.arange(1,26).reshape(5,5)

In [7]:
Ones = np.ones(25).reshape(5,5)

In [8]:
X

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [12]:
Ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.dot(X, Ones)

array([[ 15.,  15.,  15.,  15.,  15.],
       [ 40.,  40.,  40.,  40.,  40.],
       [ 65.,  65.,  65.,  65.,  65.],
       [ 90.,  90.,  90.,  90.,  90.],
       [115., 115., 115., 115., 115.]])

In [16]:
diag = np.zeros(X.shape)

In [17]:
np.fill_diagonal(diag, val=1)

In [18]:
diag

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.dot(X, diag)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25.]])

In [22]:
np.where(X >= 10, 1, 0)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
np.where(X % 2 == 0, 1, 0)

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0]])

In [24]:
np.where(X % 2 == 0, X, X+1)

array([[ 2,  2,  4,  4,  6],
       [ 6,  8,  8, 10, 10],
       [12, 12, 14, 14, 16],
       [16, 18, 18, 20, 20],
       [22, 22, 24, 24, 26]])

In [25]:
X_bis = np.where(X > 10, X*2, 0)

In [26]:
np.count_nonzero(X_bis)

15

In [27]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100], [200]])

In [29]:
np.append(x, y, axis=1)

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [30]:
print(np.append(x, y, axis=1))

[[ 10  20  30 100]
 [ 40  50  60 200]]


In [31]:
x = np.array([[10,20,30], [40,50,60]])
y = np.array([[100, 200, 300]])

In [34]:
print(np.append(x, y, axis=0))

[[ 10  20  30]
 [ 40  50  60]
 [100 200 300]]


In [35]:
np.append(x, x, axis=0)

array([[10, 20, 30],
       [40, 50, 60],
       [10, 20, 30],
       [40, 50, 60]])