In [1]:
import numpy as np

In [2]:
X = np.arange(-25, 25).reshape(10,5)

In [3]:
X

array([[-25, -24, -23, -22, -21],
       [-20, -19, -18, -17, -16],
       [-15, -14, -13, -12, -11],
       [-10,  -9,  -8,  -7,  -6],
       [ -5,  -4,  -3,  -2,  -1],
       [  0,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [12]:
ones = np.ones((X.shape[0],1))

In [13]:
ones

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [16]:
X_1 = np.append(X.copy(), ones, axis=1)

In [17]:
X_1

array([[-25., -24., -23., -22., -21.,   1.],
       [-20., -19., -18., -17., -16.,   1.],
       [-15., -14., -13., -12., -11.,   1.],
       [-10.,  -9.,  -8.,  -7.,  -6.,   1.],
       [ -5.,  -4.,  -3.,  -2.,  -1.,   1.],
       [  0.,   1.,   2.,   3.,   4.,   1.],
       [  5.,   6.,   7.,   8.,   9.,   1.],
       [ 10.,  11.,  12.,  13.,  14.,   1.],
       [ 15.,  16.,  17.,  18.,  19.,   1.],
       [ 20.,  21.,  22.,  23.,  24.,   1.]])

In [20]:
w = np.random.rand(X_1.shape[1])

In [21]:
w

array([0.15190006, 0.94163075, 0.83215925, 0.73667034, 0.16042505,
       0.34537508])

In [22]:
def predict(x, w):
    total_stimulation = np.dot(x, w)
    y_pred = 1 if total_stimulation > 0 else -1 
    return y_pred

In [23]:
predict(w,X_1[0,])

-1

In [29]:
for x in X_1:
    y_pred = predict(x, w)

In [30]:
y = np.array([1, -1, -1, 1, -1, 1, -1, -1, 1, -1])

In [35]:
eta = 0.01

In [36]:
for x, y_target in zip(X_1, y):
    y_pred = predict(x, w)
    delta_w = eta * (y_target - y_pred) * w
    w+= delta_w
    print(w)

[0.15171785 0.94050125 0.83116105 0.73578669 0.16023262 0.3449608 ]
[0.15171785 0.94050125 0.83116105 0.73578669 0.16023262 0.3449608 ]
[0.15171785 0.94050125 0.83116105 0.73578669 0.16023262 0.3449608 ]
[0.15475221 0.95931127 0.84778428 0.75050243 0.16343727 0.35186001]
[0.15475221 0.95931127 0.84778428 0.75050243 0.16343727 0.35186001]
[0.15475221 0.95931127 0.84778428 0.75050243 0.16343727 0.35186001]
[0.15165717 0.94012505 0.83082859 0.73549238 0.16016852 0.34482281]
[0.14862402 0.92132255 0.81421202 0.72078253 0.15696515 0.33792636]
[0.14862402 0.92132255 0.81421202 0.72078253 0.15696515 0.33792636]
[0.14565154 0.9028961  0.79792778 0.70636688 0.15382585 0.33116783]


In [37]:
epochs = 10

In [43]:
for _ in range(epochs):
    for x, y_target in zip(X_1, y):
        y_pred = predict(x, w)
        delta_w = eta * (y_target - y_pred) * x
        w += delta_w