In [1]:
import numpy as np

In [7]:
rand_a = np.random.rand

In [9]:
rand_a()

0.553999990895878

In [10]:
rand_a = np.random.rand(2,5)

In [11]:
rand_a

array([[0.44231205, 0.51123514, 0.65190847, 0.75879922, 0.39772393],
       [0.83232444, 0.29807368, 0.18638299, 0.78886154, 0.20842597]])

In [12]:
rand_b = np.random.rand(1,5)

In [13]:
rand_b

array([[0.64421939, 0.15611128, 0.44661884, 0.71620855, 0.09944989]])

In [14]:
rand_b = rand_b * 100

In [15]:
rand_b

array([[64.4219386 , 15.61112751, 44.66188357, 71.62085457,  9.9449894 ]])

In [16]:
rand_c = np.vstack((rand_a, rand_b))

In [17]:
rand_c

array([[ 0.44231205,  0.51123514,  0.65190847,  0.75879922,  0.39772393],
       [ 0.83232444,  0.29807368,  0.18638299,  0.78886154,  0.20842597],
       [64.4219386 , 15.61112751, 44.66188357, 71.62085457,  9.9449894 ]])

In [18]:
rand_b = np.random.rand(2,1)

In [19]:
rand_b

array([[0.10002705],
       [0.20819542]])

In [20]:
rand_c = np.hstack((rand_a, rand_b))

In [21]:
rand_c

array([[0.44231205, 0.51123514, 0.65190847, 0.75879922, 0.39772393,
        0.10002705],
       [0.83232444, 0.29807368, 0.18638299, 0.78886154, 0.20842597,
        0.20819542]])

In [24]:
X = rand_c[:,2]

In [25]:
X

array([0.65190847, 0.18638299])

In [26]:
a=3
b=8

In [27]:
y = a*X+b

In [28]:
y

array([9.95572542, 8.55914898])

In [38]:
X = np.random.randint(low=0, high=10, size = 10) 

In [39]:
X

array([4, 0, 3, 8, 6, 9, 4, 2, 6, 8])

In [40]:
X = X * 10

In [41]:
X

array([40,  0, 30, 80, 60, 90, 40, 20, 60, 80])

In [60]:
np.random.choice(10, size=3, replace=False)

array([8, 3, 6])

In [63]:
np.random.choice(10, size=5, replace=True)

array([3, 5, 7, 7, 8])

In [102]:
idx = np.random.choice(X.shape[0], size = 3, replace=False)

In [103]:
idx

array([0, 5, 9])

In [104]:
print(X)
print(idx)
print(X[idx])

[40  0 30 80 60 90 40 20 60 80]
[0 5 9]
[40 90 80]
