In [1]:
import numpy as np

In [6]:
arr = np.arange(5, 30 , 2)

In [7]:
arr

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [8]:
boolArr = arr < 10

In [9]:
arr[boolArr]

array([5, 7, 9])

In [10]:
arr[arr < 20]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [11]:
arr[arr % 3 == 0]

array([ 9, 15, 21, 27])

In [14]:
arr[(arr > 10) & (arr < 20)]

array([11, 13, 15, 17, 19])

In [15]:
arr.reshape(4,6)

ValueError: cannot reshape array of size 13 into shape (4,6)

In [17]:
arr = np.arange(24).reshape(4, 6)

In [21]:
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [54]:
arr[1]

array([ 6,  7,  8,  9, 10, 11])

In [55]:
arr[1][2]

8

In [56]:
arr[1, 2]

8

In [57]:
arr[1][2:4]

array([8, 9])

In [59]:
arr[1, 2:5]

array([ 8,  9, 10])

In [61]:
arr[1, :]

array([ 6,  7,  8,  9, 10, 11])

In [63]:
arr[:, 2]

array([ 2,  8, 14, 20])

In [68]:
arr[0:3 , 2]

array([ 2,  8, 14])

In [69]:
arr[:3, 2]

array([ 2,  8, 14])

In [72]:
arr[:3, 2:4]

array([[ 2,  3],
       [ 8,  9],
       [14, 15]])

In [77]:
arr[:, -1]

array([ 5, 11, 17, 23])

In [78]:
arr[:, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22]])

In [79]:
arr = np.arange(50).reshape(10,5)

In [80]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [81]:
#how much data should be "test-data' - here 20%
split_level = 0.2
num_rows = arr.shape[0]
split_border = split_level * num_rows

In [85]:
arr[: round(split_border), :]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
arr[round(split_border): , :]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [87]:
np.random.shuffle(arr)

In [88]:
arr

array([[40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29],
       [ 5,  6,  7,  8,  9],
       [35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24],
       [45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [90]:
arr[: round(split_border), :]

array([[40, 41, 42, 43, 44],
       [25, 26, 27, 28, 29]])

In [91]:
arr[round(split_border): , :]

array([[ 5,  6,  7,  8,  9],
       [35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24],
       [45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [92]:
data = np.arange(500).reshape(100,5)

In [93]:
np.random.shuffle(data)

In [94]:
split_level = 0.2
num_rows = data.shape[0]
split_border = split_level * num_rows 

In [95]:
X_test = data[:round(split_border), :-1]

In [96]:
X_train = data[round(split_border):, :-1]

In [97]:
Y_test = data[:round(split_border), :-1]

In [98]:
Y_train = data[round(split_border):, :-1]

In [99]:
from sklearn.model_selection import train_test_split

In [103]:
X_train, X_test, Y_train, Y_test = train_test_split(data[:,:-1], data[:, :-1], test_size=0.2, shuffle=True)

In [106]:
X_train.shape

(80, 4)

In [108]:
X_test.shape

(20, 4)

In [109]:
Y_train.shape

(80, 4)

In [110]:
Y_test.shape

(20, 4)